---
title: "datafest"
author: "Sammit Bal"
date: "2025-04-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## FrontMatter

```{r}
library(patchwork)
library(ggrepel)
library(plyr)
library(esquisse)
library(tidyverse)


maj_market_occu <- read.csv("./Major Market Occupancy Data-revised.csv")
price_avail <- read.csv("./Price and Availability Data.csv")
unem <- read.csv("./Unemployment.csv")
lease <- read.csv("./Leases.csv")
cpi <- read.csv("./US_inflation_rates.csv")
```

## Understanding the Data

```{r}
lease %>% 
  select(company_name) %>%
  unique()
```


```{r}
# colnames(maj_market_occu)
# colnames(price_avail)
# colnames(unem)
# colnames(lease)
```

```{r}
# esquisser(data = unem, viewer = "browser")
# esquisser(unem)
```

## Consolidate Industry

```{r}
# sum_industry <- lease %>%
#   filter(market == c("Manhattan", "Los Angeles", "Houston") & is.na(internal_industry) == 0) %>%
#   group_by(market, internal_industry) %>%
#   summarize(count = length(market)) %>%
#   mutate(prp = count/(sum(count))) %>%
#   ungroup()
```


```{r}
# An index of CPI per quarter
cpi_q <- cpi %>%
  mutate(year = substr(date, 1, 4)) %>%
  mutate(month = substr(date, 6, 7)) %>%
  filter(month %in% c("03", "06", "09", "12")) %>%
  mutate(quarter = case_when(
                          month == "03" ~ ".Q1", 
                          month == "06" ~ ".Q2", 
                          month == "09" ~ ".Q3", 
                          month == "12" ~ ".Q4")) %>%
  mutate(year_quarter = paste(year, quarter, sep = "")) %>%
  rename(cpi = value) %>%
  select(year_quarter, cpi)

# Appending additional (2024) data on CPI
## Source: https://www.usinflationcalculator.com/inflation/consumer-price-index-and-annual-percent-changes-from-1913-to-2008/
cpi_2024_q <- data.frame(
  year_quarter = c("2023.Q3", "2023.Q4", "2024.Q1", "2024.Q2", "2024.Q3", "2024.Q4"),
  cpi = c(296.808, 296.797, 301.836, 305.109, 307.789, 306.746)
)

cpi_q <- rbind(cpi_q, cpi_2024_q)

# A function for matching a quarter to a value
get_cpi_q <- function(time) {
    return(cpi_q %>% filter(year_quarter == time) %>% select(cpi))
}
```


Make Rent, Occupancy, and Availability  graphs for Manhattan, LA, Houston



```{r side-by-side-patchwork, message=FALSE, fig.width=15}
############################# Rent #########################################

# Combine rent data for all 3 cities
combined_rent_data <- lease %>%
  filter(market %in% c("Manhattan", "Los Angeles", "Houston")) %>%
  mutate(time = paste(year, ".", quarter, sep = "")) %>%
  group_by(market, time) %>%
  summarize(avg_rent = mean(overall_rent, na.rm = TRUE)) %>%
  arrange(market, time)

# Convert 'time' to ordered factor
combined_rent_data$time <- factor(combined_rent_data$time, 
                                  levels = unique(combined_rent_data$time), 
                                  ordered = TRUE)

combined_rent_plot <- ggplot(combined_rent_data, aes(x = time, y = avg_rent, color = market, group = market)) +
  geom_line(size = 1.2) +
  geom_point() +
  geom_vline(xintercept = which(levels(combined_rent_data$time) == "2020.Q1"), 
             linetype = "dashed", color = "gray40", size = 1) +
  annotate("text", 
           x = which(levels(combined_rent_data$time) == "2020.Q1"), 
           y = Inf, 
           label = "COVID Begins                           ", 
           vjust = -0.5, angle = 90, size = 3, color = "gray40") +
  geom_vline(xintercept = which(levels(combined_rent_data$time) == "2023.Q2"), 
             linetype = "dashed", color = "gray40", size = 1) +
  annotate("text", 
           x = which(levels(combined_rent_data$time) == "2023.Q2"), 
           y = Inf, 
           label = "COVID Ends                           ", 
           vjust = -0.5, angle = 90, size = 3, color = "gray40") +
  labs(
    title = "Overall Rent Trends (2018–2024)",
    subtitle = "Comparison across Manhattan, Los Angeles, and Houston",
    x = "Quarter",
    y = "Average Rent\n(USD per sq ft/year)",
    color = "Market"
  ) +
  theme_minimal(base_size = 12) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

############################# Rent (inf. adj.) ######################################
# Appending CPI values to combined_rent_data
cpi_2018q1 <- as.numeric(get_cpi_q('2018.Q1'))

combined_rent_data_adj <- lease %>%
  filter(market %in% c("Manhattan", "Los Angeles", "Houston")) %>%
  mutate(time = paste(year, ".", quarter, sep = "")) %>%
  left_join(cpi_q, by = c("time" = "year_quarter")) %>%
  mutate(overall_rent_adj = overall_rent * cpi_2018q1 / cpi) %>%
  group_by(market, time) %>%
  summarize(avg_rent_adj = mean(overall_rent_adj, na.rm = TRUE)) %>%
  arrange(market, time)

# Visualization adj. for CPI (inflation)
combined_rent_plot_adj <- ggplot(combined_rent_data_adj, aes(x = time,
                                   y = avg_rent_adj,
                                   color = market,
                                   group = market)) +
  geom_line(size = 1.2) +
  geom_point() +
  geom_vline(xintercept = which(levels(combined_rent_data$time) == "2020.Q1"), 
             linetype = "dashed", color = "gray40", size = 1) +
  annotate("text", 
           x = which(levels(combined_rent_data$time) == "2020.Q1"), 
           y = Inf, 
           label = "COVID Begins                           ", 
           vjust = -0.5, angle = 90, size = 3, color = "gray40") +
  geom_vline(xintercept = which(levels(combined_rent_data$time) == "2023.Q2"), 
             linetype = "dashed", color = "gray40", size = 1) +
  annotate("text", 
           x = which(levels(combined_rent_data$time) == "2023.Q2"), 
           y = Inf, 
           label = "COVID Ends                           ", 
           vjust = -0.5, angle = 90, size = 3, color = "gray40") +
  labs(
    title = "Overall Rent Trends, Adjusted for Inflation (2018–2024)",
    subtitle = "Comparison across Manhattan, Los Angeles, and Houston",
    x = "Quarter",
    y = "Average Rent Adjusted for Inflation\n(USD per sq ft/year)",
    color = "Market",
    caption = "Note: All USD values are adjusted relative to 2018 Q1's Consumer Price Index"
  ) +
  scale_y_continuous(breaks = seq(20, 100, 10)) + 
  theme_minimal(base_size = 12) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

combined_rent_plot + combined_rent_plot_adj
```

```{r}
############################## Availability ################################
combined_avail_data <- lease %>%
  filter(market %in% c("Manhattan", "Los Angeles", "Houston")) %>%
  mutate(time = paste(year, ".", quarter, sep = "")) %>%
  group_by(market, time) %>%
  summarize(availability_proportion = first(availability_proportion)) %>%
  arrange(market, time)

combined_avail_data$time <- factor(combined_avail_data$time, levels = unique(combined_avail_data$time), ordered = TRUE)

combined_avail_plot <- ggplot(combined_avail_data, aes(x = time, y = availability_proportion * 100, color = market, group = market)) +
  geom_line(size = 1.2) +
  geom_point() +
  geom_vline(xintercept = which(levels(combined_avail_data$time) == "2020.Q1"), 
             linetype = "dashed", color = "gray40", size = 1) +
  annotate("text", 
           x = which(levels(combined_avail_data$time) == "2020.Q1"), 
           y = Inf, 
           label = "COVID Begins                           ", 
           vjust = -0.5, angle = 90, size = 3, color = "gray40") +
  geom_vline(xintercept = which(levels(combined_avail_data$time) == "2023.Q2"), 
             linetype = "dashed", color = "gray40", size = 1) +
  annotate("text", 
           x = which(levels(combined_avail_data$time) == "2023.Q2"), 
           y = Inf, 
           label = "COVID Ends                           ", 
           vjust = -0.5, angle = 90, size = 3, color = "gray40") +
  labs(
    title = "Availability Proportion Trends (2018–2024)",
    subtitle = "Comparison across Manhattan, Los Angeles, and Houston",
    x = "Quarter",
    y = "Availability (%)",
    color = "Market"
  ) +
  theme_minimal(base_size = 12) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

print(combined_avail_plot)
```

```{r}
############################## Occupancy ####################################
combined_occupancy_data <- maj_market_occu %>%
  filter(market %in% c("Manhattan", "Los Angeles", "Houston")) %>%
  mutate(time = paste(year, ".", quarter, sep = "")) %>%
  arrange(market, year, quarter)

combined_occupancy_data$time <- factor(combined_occupancy_data$time, levels = unique(combined_occupancy_data$time), ordered = TRUE)

combined_occupancy_plot <- ggplot(combined_occupancy_data, aes(x = time, y = avg_occupancy_proportion * 100, color = market, group = market)) +
  geom_line(size = 1.2) +
  geom_point() +
  labs(
    title = "Occupancy Proportion Trends (2020–2024 Q3)",
    subtitle = "Comparison across Manhattan, Los Angeles, and Houston",
    x = "Quarter",
    y = "Occupancy (%)",
    color = "Market"
  ) +
  geom_vline(xintercept = which(levels(combined_occupancy_data$time) == "2020.Q1"), 
             linetype = "dashed", color = "gray40", size = 1) +
  annotate("text", 
           x = which(levels(combined_occupancy_data$time) == "2020.Q1"), 
           y = Inf, 
           label = "COVID Begins                           ", 
           vjust = -0.5, angle = 90, size = 3, color = "gray40") +
  geom_vline(xintercept = which(levels(combined_occupancy_data$time) == "2023.Q2"), 
             linetype = "dashed", color = "gray40", size = 1) +
  annotate("text", 
           x = which(levels(combined_occupancy_data$time) == "2023.Q2"), 
           y = Inf, 
           label = "COVID Ends                           ", 
           vjust = -0.5, angle = 90, size = 3, color = "gray40") +
  theme_minimal(base_size = 12) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

print(combined_occupancy_plot)

#ggsave("Plots/combined_rent_trend.png", plot = combined_rent_plot, width = 8, height = 5, dpi = 300)
#ggsave("Plots/combined_availability_trend.png", plot = combined_avail_plot, width = 8, height = 5, dpi = 300)
#ggsave("Plots/combined_occupancy_trend.png", plot = combined_occupancy_plot, width = 8, height = 5, dpi = 300)
```


Histogram for each city for sublet available space.


```{r}
# ===================== Sublet Available Space =================================
combined_sublet_data <- lease %>%
  filter(market %in% c("Manhattan", "Los Angeles", "Houston")) %>%
  filter(substr(year, 1, 4) %in% c("2019", "2020", "2021", "2022", "2023", "2024")) %>%
  mutate(time = paste(year, ".", quarter, sep = "")) %>%
  group_by(market, time) %>%
  mutate(sub_avail_space_bil = as.numeric(sublet_available_space) / 1e9) %>%
  summarize(sublet_space_bil = sum(sub_avail_space_bil, na.rm = TRUE)) %>%
  arrange(market, time)

# Convert time to ordered factor
combined_sublet_data$time <- factor(combined_sublet_data$time, levels = unique(combined_sublet_data$time), ordered = TRUE)

# Plot
combined_sublet_plot <- ggplot(combined_sublet_data, 
                               aes(x = time, y = sublet_space_bil, 
                                   color = market, group = market)) +
  geom_line(size = 1.2) +
  geom_point() +
  geom_vline(xintercept = which(levels(combined_sublet_data$time) == "2020.Q1"), 
             linetype = "dashed", color = "gray40", size = 1) +
  annotate("text", 
           x = which(levels(combined_sublet_data$time) == "2020.Q1"), 
           y = Inf, 
           label = "COVID Begins                           ", 
           vjust = -0.5, angle = 90, size = 3, color = "gray40") +
  geom_vline(xintercept = which(levels(combined_sublet_data$time) == "2023.Q2"), 
             linetype = "dashed", color = "gray40", size = 1) +
  annotate("text", 
           x = which(levels(combined_sublet_data$time) == "2023.Q2"), 
           y = Inf, 
           label = "COVID Ends                           ", 
           vjust = -0.5, angle = 90, size = 3, color = "gray40") +
  labs(
    title = "Sublet Available Space Trends (2019–2024)",
    subtitle = "Total square footage across Manhattan, Los Angeles, and Houston",
    x = "Quarter",
    y = "Sublet Available Space\n(billions of sq ft)",
    color = "Market"
  ) +
  theme_minimal(base_size = 12) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

print(combined_sublet_plot)

ggsave("Plots/combined_sublet_plot.png", plot = combined_sublet_plot, width = 8, height = 5, dpi = 300)


```

Number of lease entries for each city


```{r}
lease %>%
  group_by(market) %>%
  summarise(nmarket = n()) %>%
  arrange(desc(nmarket))
```


```{r side-by-side-patchwork, message=FALSE, fig.width=20}
# =========================== Leasing Trends =================================
# Lease 3C = Leases across 3 cities
three_mc <- c("Los Angeles", "Manhattan", "Houston")
lease_3c <- lease %>% 
  filter(market == three_mc) %>%
  filter(!is.na(space_type)) %>%
  mutate(avail_space_mil = available_space / 1e6) %>%
  mutate(RentSublet = ifelse(space_type == "New", "New", "Rental / Rental Sublet Space")) %>%
  mutate(year_range = round(year / 2) * 2) %>%
  mutate(year_range = factor(year_range, levels = c("2018", "2020", "2022", "2024"),
                             labels = c("2018", "2019-2020", "2021-2022", "2023-2024")))

lease_3c.cor <- ddply(.data=lease_3c, 
                 .(RentSublet, year_range, market), 
                 summarize, 
                 n = ifelse(length(market) > 30, 
                            "", paste("n = ", length(market))))

quartiles <- lease_3c %>%
  mutate(y_round = round(avail_space_mil, 0)) %>%
  group_by(market, RentSublet, year_range) %>%
  reframe(y = quantile(y_round, c(.5))) 

ggplot(data = lease_3c,
       mapping = aes(
         x = market,
         y = avail_space_mil, 
         fill = market))  +
  geom_boxplot() + 
  facet_grid(RentSublet ~ year_range) + 
  geom_text_repel(
    data = quartiles,
    aes(x = market,
        y = y,
        label = y
    ),
    nudge_x = 0.4,
    hjust = 0, 
    size = 5) + 
  geom_text(data=lease_3c.cor, aes(x=market, y=55, label=n), 
                    colour="red", inherit.aes=FALSE, parse=FALSE, size = 5) + 
  labs(y = "Available Rental Space\n(millions of sq. ft.)",
       x = "City", 
       caption = "Note: Histograms without an `n` value are greater than size 30", 
       title = "New vs Rental/Rental Sublet Space Availability (2018-2024)",
       subtitle = "Comparison across Manhattan, Los Angeles, and Houston") + 
  theme(legend.position = "none", 
        plot.title = element_text(size = 25),
        plot.subtitle = element_text(size = 20),
        axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 10),
        axis.title.x = element_text(size = 25),
        axis.title.y = element_text(size = 15), 
        plot.caption = element_text(size = 20, color = "darkred", face = "bold"),
        strip.text.x = element_text(size = 15),
        strip.text.y = element_text(size = 15)
        )
```

